language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8

after_success:
- codecov
- mvn package -pl ugs-core assembly:assembly
- mvn install
- mvn package -pl ugs-platform/application -P deployment,autoupdate -DskipTests=true

before_script:
- pip install --user codecov
- curl -fL https://getcli.jfrog.io | sh
- ./jfrog rt config --interactive false --url $ARTIFACTORY_URL --user $ARTIFACTORY_LOGIN --apikey $ARTIFACTORY_PASSWORD
  # Classic Jar
- ./jfrog rt u "ugs-core/target/UniversalGcodeSender.jar" UGS --build-name=$ARTIFACTORY_NAME --build-number=$TRAVIS_BUILD_NUMBER --flat=false
  # Platform - agnostic zip
- ./jfrog rt u "ugs-platform/application/target/ugs-platform-app-*.zip" UGS --build-name=$ARTIFACTORY_NAME --build-number=1 --flat=false
  # Installers...
  #   TODO
  # Autoupdate site
- ./jfrog rt u "ugs-platform/application/target/site/netbeans_site/" "UGS/update-center/" --build-name=$ARTIFACTORY_NAME --build-number=$TRAVIS_BUILD_NUMBER
  # Publish artifacts
- ./jfrog rt bce $ARTIFACTORY_NAME $TRAVIS_BUILD_NUMBER
- ./jfrog rt bp $ARTIFACTORY_NAME $TRAVIS_BUILD_NUMBER

env:
  global:
    - ARTIFACTORY_NAME=ugs
      # Disable jfrog CLI prompts.
    - JFROG_CLI_OFFER_CONFIG=false

